// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace TestingDemo.Infrastructure.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSalary : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSalary));
        
        string IMigrationMetadata.Id
        {
            get { return "201510081332174_AddSalary"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
